### ISSUE TITLE
Overwriting files does not work

### ISSUE THREAD

**Issue by Luflosi** [linux-apfs/linux-apfs-rw#14]
Executing `echo test > test.txt` twice on a readwrite mounted APFS filesystem prints "operation not supported: test.txt" and does not overwrite the file.

Is this something you plan to support in the future? How much work would it be to implement this?

**Comment by eafer** [comment]
Right, truncation is not implemented yet, you can only append to files. I'm working on it now, you may see it in two weeks or so.
