### ISSUE TITLE
/lib/modules/5.13.9-arch1-1/build: No such file or directory.  Stop.

### ISSUE THREAD

**Issue by n8jadams** [linux-apfs/linux-apfs-rw#16]
I am on Arch, so I simply downloaded `linux-headers` from pacman, cloned the repo, `cd`'d into the repo, ran `make` and got this error:

```
make -C /lib/modules/5.13.9-arch1-1/build M=/home/nate/linux-apfs-rw
make[1]: *** /lib/modules/5.13.9-arch1-1/build: No such file or directory.  Stop.
make: *** [Makefile:15: default] Error 2
```

Did I miss something?

EDIT: in `/lib/modules` I have a folder called `5.13.12-arch1-1`... Do I need that specific version for this to work?

**Comment by eafer** [comment]
I've never tried to build this on Arch, so I guess the instructions could be wrong.

>  in /lib/modules I have a folder called 5.13.12-arch1-1... Do I need that specific version for this to work?

The makefile is getting your kernel version from `uname -r`, so you seem to be using 5.13.9-arch1-1, and your distro gave you the headers for 5.13.12-arch1-1. I don't know anything about Arch, but maybe you are expected to upgrade the kernel? Or maybe you upgraded already and didn't reboot?

I think you should be able to build with the version mismatch though, if you want you can try:

>make KERNELRELEASE="5.13.12-arch1-1"

**Comment by n8jadams** [comment]
Yeah, that was it. user error. I had updated my Arch system `pacman -Syu` and hadn't yet rebooted before trying to run the makefile.
