### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by Dekedro** [linux-apfs/linux-apfs-rw#18]
Source files currently contain headers with `SPDX-License-Identifier: GPL-2.0`. However, as per https://spdx.org/licenses/, there is no such license identifier, I am assuming it was meant to be "GPL-2.0-only" or "GPL-2.0-or-later". Please clarify which version is used by this project.

**Comment by eafer** [comment]
> there is no such license identifier

Yes there is, it's in the list of deprecated identifiers.

**Comment by Dekedro** [comment]
> Yes there is, it's on the list of deprecated identifiers.

Missed that, thanks.

So one can assume that this project is under "GPL-2.0-only"? I think it would be nice to update headers anyway.

**Comment by eafer** [comment]
Yes, its GPL 2.0 only. I didn't know about the deprecation, so I guess I'll change the headers soon.
