### ISSUE TITLE
super.c: In function ‘apfs_setup_bdi’:

### ISSUE THREAD

**Issue by hellisabove** [linux-apfs/linux-apfs-rw#21]
super.c:1072:31: error: ‘struct block_device’ has no member named ‘bd_bdi’
 1072 |         bdi_dev = nxi->nx_bdev->bd_bdi;

**Comment by hellisabove** [comment]
I found out that this issue happens after the latest commit which is [this](https://github.com/linux-apfs/linux-apfs-rw/commit/f248fc88439da07732e5bd3bdd09576913aac16a). By forcing git to use an older commit, the project builds and works correctly

**Comment by eafer** [comment]
Hi, thanks for the report. I pushed a patch for this to the development branch, when you can let me know if it solves the problem for you.

**Comment by hellisabove** [comment]
Hey, building and installing now works. Thanks for seeing this!
