### ISSUE TITLE
mount -t apfs device mountpoint   

### ISSUE THREAD

**Issue by hoan3504** [linux-apfs/linux-apfs-rw#22]
mounting apfs looks ok ...but the files inside the tree structure are almost empty
I have mac's rootfs from a working virtual mac (I can play jessica rhaye singing  bob dylan on youtube ; so it is really working)
all the filenames in directory tree look quite normal ... but its contents are simply 0
I have just followed prescription make; modprobe libcrc... and insmod apfs.ko
I am not aiming at modifying files in apfs ,but just willing to clone a apfs_mojave back into hfs_mojave using tar between the 2 filesytems
 under linux instead of using CCC carbone clone copy
thank you

**Comment by eafer** [comment]
That sounds like an unsupported compression algorithm. Only zlib works for now, sorry. I will try to add the others in the coming months.

**Comment by eafer** [comment]
All known compression algorithms should be supported now in the development branch. Since it's been more than a year and you may not care anymore, I'm just closing this issue without waiting for confirmation. Feel free to reopen if you try it out and run into problems.
