### ISSUE TITLE
umount cause NULL dereference

### ISSUE THREAD

**Issue by zvova7890** [linux-apfs/linux-apfs-rw#27]
I have mounted apfs partition, created by Catalina. No problems, mount's fine, ls /mnt I can see files, after that I'm umount directory and got backtrace. I'm using 5.18.10-zen1-1-zen kernel on archlinux.
[dmesg.txt](https://github.com/linux-apfs/linux-apfs-rw/files/9093884/dmesg.txt)

**Comment by eafer** [comment]
How did you get it to build? Were you using [this patch](https://github.com/linux-apfs/linux-apfs-rw/pull/24)?

**Comment by zvova7890** [comment]
Yes, I look at the nop function and thought what bad gonna happen? :)

**Comment by eafer** [comment]
Haha yes, everything collapses in my tests too. I think I have a better solution, I'll push it soon.

**Comment by eafer** [comment]
I just pushed something that builds and looks correct, but I haven't tested it yet. When you can let me know if it helps with your problem.

**Comment by zvova7890** [comment]
I built a development branch, builds fine, but same behavior while umount

**Comment by eafer** [comment]
> I built a development branch, builds fine, but same behavior while umount

Thanks. I guess this is a separate issue then.

**Comment by eafer** [comment]
I think it's fixed now.

**Comment by zvova7890** [comment]
Yes it is! Thank you!
