### ISSUE TITLE
Build errors with kver. 6.0.9

### ISSUE THREAD

**Issue by sergiall** [linux-apfs/linux-apfs-rw#32]
Sorry for my bad franch, but i have this issue at modpost stage:

ERROR: modpost: "__umoddi3" [fs/apfs/apfs.ko] undefined!
ERROR: modpost: "__udivdi3" [fs/apfs/apfs.ko] undefined !

And I dont know what do me do!

inxi -Fxz:
System:
  Kernel: 6.0.2-zen-060002-generic++ arch: i686 bits: 32 compiler: gcc
    v: 12.2.0 Desktop: N/A Distro: Debian GNU/Linux bookworm/sid
Machine:
  Type: Laptop System: Acer product: TravelMate 5320 v: 0100
    serial: <superuser required>
  Mobo: Acer model: Columbia v: Rev serial: <superuser required>
    BIOS: Phoenix v: 1.21 date: 10/05/2007
CPU:
  Info: dual core model: Intel Core2 Duo T7500 bits: 64 type: MCP
    arch: Core2 Merom rev: B cache: L1: 128 KiB L2: 4 MiB
  Speed (MHz): avg: 798 min/max: 800/2201 boost: enabled cores: 1: 798
    2: 798 bogomips: 8779
  Flags: ht lm nx pae sse sse2 sse3 ssse3 vmx
Graphics:
  Device-1: Intel Mobile GM965/GL960 Integrated Graphics
    vendor: Acer Incorporated ALI driver: i915 v: kernel arch: Gen-4
    bus-ID: 00:02.0
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.5 driver:
    dri: crocus gpu: i915 note: X driver n/a resolution: 1280x800~60Hz
  API: OpenGL v: 2.1 Mesa 22.2.4 renderer: Mesa Intel 965GM (CL)
    direct render: Yes
Audio:
  Device-1: Intel 82801H HD Audio vendor: Acer Incorporated ALI Realtek
    ALC268 codec driver: snd_hda_intel v: kernel bus-ID: 00:1b.0
  Sound API: ALSA v: k6.0.2-zen-060002-generic++ running: yes
  Sound Server-1: PulseAudio v: 16.1 running: yes
  Sound Server-2: PipeWire v: 0.3.60 running: no
Network:
  Device-1: Broadcom NetLink BCM5787M Gigabit Ethernet PCI Express
    vendor: Acer Incorporated ALI driver: tg3 v: kernel port: N/A
    bus-ID: 02:00.0
  IF: enp2s0 state: up speed: 100 Mbps duplex: full mac: <filter>
  Device-2: Broadcom BCM4311 802.11b/g WLAN vendor: AMBIT Microsystem
    driver: b43-pci-bridge v: N/A bus-ID: 04:00.0
  IF-ID-1: erspan0 state: down mac: <filter>
  IF-ID-2: gre0 state: down mac: <filter>
  IF-ID-3: gretap0 state: down mac: <filter>
  IF-ID-4: ip6tnl0 state: down mac: <filter>
  IF-ID-5: tunl0 state: down mac: <filter>
  IF-ID-6: wlan0 state: down mac: <filter>
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) type: USB
    driver: btusb v: 0.8 bus-ID: 5-1.4:4
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1
    lmp-v: 4.0
Drives:
  Local Storage: total: 1.06 TiB used: 483.18 GiB (44.7%)
  ID-1: /dev/sda vendor: Hitachi model: HTS542516K9SA00 size: 149.05 GiB
  ID-2: /dev/sdb type: USB vendor: Western Digital
    model: WD50 00LPVX-80V0TT0 size: 465.76 GiB
  ID-3: /dev/sdc type: USB vendor: Western Digital model: WD5000LPVX-22V0TT0
    size: 465.76 GiB
Partition:
  ID-1: / size: 29.36 GiB used: 27.83 GiB (94.8%) fs: ext4 dev: /dev/sdc9
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 38 MiB (0.9%) dev: /dev/sdc5
Sensors:
  System Temperatures: cpu: 51.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Info:
  Processes: 196 Uptime: 23m Memory: 1.95 GiB used: 1.53 GiB (78.5%)
  Init: SysVinit runlevel: 2 Compilers: gcc: 12.2.0 clang: 14.0.6-6
  Packages: 6134 Shell: Bash v: 5.2.2 inxi: 3.3.23

Early I saccifuly build etch kver with apfs as kernel module and thats work fine, but now ((__

**Comment by eafer** [comment]
Hi, thanks for the report. This error is seen when you try to perform 64-bit divisions on 32-bit architectures. I don't have any 32-bit machines these days, so it seems that I messed that up at some point. The fix is to find those divisions and replace them with calls to DO_DIV(). I'm a bit busy right now, I'll get to it in a few days.

**Comment by sergiall** [comment]
Thank with my regard, I will try too...

**Comment by eafer** [comment]
Sorry for the delay, I just pushed a patch that should take care of this. Let me know if you are still having any problems.

**Comment by eafer** [comment]
This is probably fine so I'm closing it for now, feel free to reopen if it doesn't work for you.
