### ISSUE TITLE
requires 

### ISSUE THREAD

**Issue by flopflip** [linux-apfs/linux-apfs-rw#34]
I am on kernel 6.1 in asahi linux, and trying to make (after installing headers) throws error that it requires kernel 5.18?

**Comment by eafer** [comment]
Hi, thanks for the report. I don't have avahi, but I just attempted a build with Linux 6.1 on debian and it seemed to work fine. Can you share any more details? The exact error message might help.

**Comment by flopflip** [comment]
Hello,
Thank you for replying,

Asahi Linux is the only way currently to run linux on a MacBook, so it’s the major case
for using APFS on linux - but it may be buggy...

Here’s what I get - it looks like it wants a specific version and it does not want to use the newer one:

==> Making package: linux-apfs-rw-dkms-git 1:r169.e6eb67c-1 (Fri Jan 13 11:47:29 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
 -> Updating linux-apfs-rw git repo...
fatal: unable to access 'https://github.com/linux-apfs/linux-apfs-rw.git/': Could not resolve host: github.com<http://github.com/>
==> WARNING: Failure while updating linux-apfs-rw git repo
==> Validating source files with sha256sums...
   linux-apfs-rw ... Skipped
==> Extracting sources...
 -> Creating working copy of linux-apfs-rw git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> WARNING: A package has already been built, installing existing package...
==> Installing package linux-apfs-rw-dkms-git with pacman -U...
[sudo] password for boba:
loading packages...
warning: linux-apfs-rw-dkms-git-1:r169.e6eb67c-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) linux-apfs-rw-dkms-git-1:r169.e6eb67c-1

Total Installed Size:  0.57 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                     [####################################] 100%
(1/1) checking package integrity                                   [####################################] 100%
(1/1) loading package files                                        [####################################] 100%
(1/1) checking for file conflicts                                  [####################################] 100%
(1/1) checking available disk space                                [####################################] 100%
:: Running pre-transaction hooks...
(1/1) Remove upgraded DKMS modules
:: Processing package changes...
(1/1) reinstalling linux-apfs-rw-dkms-git                          [####################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> ERROR: Missing 5.19.8-1-aarch64-ARCH kernel modules tree for module linux-apfs-rw/0.2.


On 12 Jan 2023, at 23:29, Ernesto Fernández ***@***.***> wrote:



Hi, thanks for the report. I don't have avahi, but I just attempted a build with Linux 6.1 on debian and it seemed to work fine. Can you share any more details? The exact error message might help.

**Comment by eafer** [comment]
This is the AUR package you are installing right? Maybe you can report this to the package maintainer over there?

Your original comment seemed to imply that you were building the driver directly, do you still get this problem when you do that? Can you show me the error message you get in that case?

**Comment by flopflip** [comment]
Hi,

I installed from GitHub, not AUR, seemed to compile and build the package OK but could not install it,
It looks like it insists on a specific version of header rather than accepting new ones.

I am not sure if it’s a problem with your code, maybe it’s Asahi linux which is still alpha.

I guess maybe I could ask you to check for any “version==X” in your code and
replace them with “version>=X”..

Cheers,
Evan


On 13 Jan 2023, at 23:46, Ernesto Fernández ***@***.***> wrote:



This is the AUR package you are installing right? Maybe you can report this to the package maintainer over there?

Your original comment seemed to imply that you were building the driver directly, do you still get this problem when you do that? Can you show me the error message you get in that case?

**Comment by eafer** [comment]
> I installed from GitHub, not AUR, seemed to compile and build the package OK but could not install it

I'm still a bit confused here. What package are you talking about? My repo only has a `Makefile` and a `dkms.conf` file. Are you getting a `PKGBUILD` from somewhere else, or making your own?

**Comment by eafer** [comment]
I don't think there's much I can do here, so I'll close this issue. Feel free to reopen if you disagree.

**Comment by flopflip** [comment]
Hi Ernesto,

I was able to install by manually removing some kernel headers, but
It’s not mounting APFS because it now throws “driver not configured in kernel”,

Would it be possible to post some instructions on how to configure
the driver in the kernel once it is installed?

Cheers,
Doof




On 24 Mar 2023, at 3:04, Ernesto Fernández ***@***.***> wrote:



I don't think there's much I can do here, so I'll close this issue. Feel free to reopen if you disagree.

**Comment by eafer** [comment]
Is "driver not configured in kernel" the exact error message you are getting? Which tool threw the error? I can't find that string in the kernel.

> Would it be possible to post some instructions on how to configure the driver in the kernel once it is installed?

It's not clear to me what you mean by "configure" or "install" here. Maybe you are asking about dkms? Are you still using the same `PKGBUILD` file from before? Where did you get it?

**Comment by flopflip** [comment]
so the driver is installed successfully with make and then when I try to mount an APFS volume, this is the error: "the driver is not configured in the kernel"

**Comment by eafer** [comment]
Have you inserted the module? What do you get if you run `lsmod | grep apfs`?

**Comment by BlackMage2** [comment]
can be the title of this issue changed? 'requires' is meaningless

**Comment by eafer** [comment]
I don't think the title matters much, but we're not going to make any progress on this one, so I might as well close it.
