### ISSUE TITLE
tagging a release?

### ISSUE THREAD

**Issue by alexmyczko** [linux-apfs/linux-apfs-rw#36]
i see the latest commit 0.3.0, would it be hard to tag a release? would make looking at

https://repology.org/project/apfs/versions

much easier?

**Comment by Luflosi** [comment]
It exists already: https://github.com/linux-apfs/linux-apfs-rw/releases/tag/v0.3.0

**Comment by alexmyczko** [comment]
Ahh it's just not shown in the mainpage, as it probably has been configured to not show up :( my bad for not checking harder to find it. thanks

**Comment by eafer** [comment]
I don't know why the releases are not listed, I never configured that. I find github terribly confusing sometimes. I can't get it to report the tag as "verified" either, even though I uploaded my public key and all.

**Comment by alexmyczko** [comment]
and debian just got 0.3.0 :) thanks
