### ISSUE TITLE
Trying to mount a RAID

### ISSUE THREAD

**Issue by rafacampoamor** [linux-apfs/linux-apfs-rw#37]
Hi!

I'm trying to mount an APFS encrypted drive, but I don't get which command to use.
I've tried with :
`sudo apfs-fuse -r PASSWORD /dev/sdb1 /mnt/raid`
getting:
`This doesn't seem to be an apfs volume (invalid superblock).
Unable to load container.`

`sudo apfs-fuse -r PASSWORD /dev/sdb3 /mnt/raid`
getting the same.

And
`sudo apfs-fuse -r PASSWORD /dev/sdb2 /mnt/raid`
getting:
`ERROR: Invalid omap block @ oid 0x5d6a64
Failed to load nx omap
Unable to load container.`

I've been looking around but couldn't get how to mount a RAID

Anyone can help me?

**Comment by Luflosi** [comment]
This is the wrong repo, you're looking for https://github.com/sgan81/apfs-fuse.

**Comment by rafacampoamor** [comment]
Oh, sorry!
