### ISSUE TITLE
FOR WSL2?

### ISSUE THREAD

**Issue by TephrocactusHC** [linux-apfs/linux-apfs-rw#40]
Excuse me, do you happen to know if this is compatible with WSL2? I tried a few things, but unfortunately, it didn't work out.

**Comment by eafer** [comment]
I'm sorry, I've never used WSL2. From what I'm reading, it seems that it should work, but you may have to build your own kernel.

**Comment by eafer** [comment]
I guess I can close this now. Feel free to reopen if you have any more questions.
