### ISSUE TITLE
No rw access (but Win isn't further in here)

### ISSUE THREAD

**Issue by lizbethmutterhunt** [linux-apfs/linux-apfs-rw#41]
To be built was a CUSTOM kernel with option CONFIG_MODULE_SIG=n to avoid signing the apfs.ko.zst module. Driver loads fine, but I still have now read-write, because of backup files from time machine on SSD. It's at the moment not possible to mount this rw, although urgently necessary, because of installed NVIDIA-driver, incompatible with the GTX-970 by shitty proprietary NVIDIA. Any suggestions. My way to do is to boot recovery, delete the ssd with ventura 13.4 beta 3 and reinstall, then take back the data from time machine @ setup. Any easier suggestions; I just need to delete some .kexts in the /System/Extensions/ - Folder. .

In Windows I tried cracked Paragon Software or a free trial, but same stuff, because of backups on a seperate Time Machine on a 2TB hdd it isn't possible to assign a letter for rw!

**Comment by eafer** [comment]
You probably don't care about this ticket anymore, so I'm closing it. Feel free to reopen if you disagree.
