### ISSUE TITLE
Please mention a list of alternative APFS mount tools, and the pros and cons of each, if you are aware of any

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [linux-apfs/linux-apfs-rw#42]
I think it would be nice to have an "alternatives" section in the readme where you discuss the various APFS mount options (counting yours) and the pros and cons of each--or at least _mention_ any alternatives you are aware of, to help us users make sense of each. 

Here are the several I am aware of now:
1. https://github.com/sgan81/apfs-fuse
2. https://github.com/linux-apfs/linux-apfs-rw [this one]
3. https://github.com/libyal/libfsapfs
4. https://www.paragon-software.com/us/home/apfs-linux/ [paid, but I'd bet it's the best]

References:
1. [SuperUser: How to mount APFS on Linux or Windows?](https://superuser.com/q/1267291/425838)

**Comment by eafer** [comment]
>I think it would be nice to have an "alternatives" section in the readme

I guess I can do that eventually. For now I'll tell you here quickly:

> https://github.com/sgan81/apfs-fuse

This is a fuse driver, not a kernel driver. So it's probably more portable, but it's also much slower. Unlike mine it also supports encryption, but it has no write support and I don't think there are any plans for it either.

> https://github.com/libyal/libfsapfs

I've never used this one (though I did get some layout information from the author's work). The first obvious difference is that it's a library. So again, more portable than mine, but you can't use it to actually mount the filesystem. You will need to work exclusively with the tools the author provides, or build your own.

Assuming the README is up to date, it seems to be missing support for snapshots and several compression algorithms, which are all supported in my driver (and also in the fuse driver, I believe). I don't know where it stands in some stuff it doesn't mention, like sealed volumes. I'm guessing those are not implemented. It does support encryption though.

Like the fuse driver, this one is also read-only, and there are no plans for write support as far as I can see.

> https://www.paragon-software.com/us/home/apfs-linux/ [paid, but I'd bet it's the best]

The main disadvantage of this one is that it's paid and closed-source. I've never used it (I'm assuming it's expensive?), so I can't talk about its quality, sorry. It's probably much more complete than mine, and they don't use the 'experimental' disclaimer like I do, so they must be confident that the writes work correctly. Nobody likes to lose data though, and we don't know much about its development process, so if you are interested in this option you should talk to other customers and see if it's reliable.

**Comment by ElectricRCAircraftGuy** [comment]
This is very helpful. Thank you. 

By the way, I have used your tool to recover files on a 2015 MacBook via an Ubuntu 22.04 live USB, and it is really easy to mount, since it works with the built-in file manager GUIs to just click the drive and it auto-mounts!

Please keep developing it! I'm very impressed, and would love to see it work really well and support **encrypted systems** and reliable **writing**. 

For anyone wondering, **here is how I install it on an Ubuntu 22.04 live USB** booted on a 2015 MacBook with an *un*encrypted APFS filesystem on the MacBook:

```bash
sudo add-apt-repository universe
sudo apt update  
sudo apt install git gcc g++ cmake make ncdu
sudo apt install linux-headers-$(uname -r)

cd ~
git clone https://github.com/linux-apfs/linux-apfs-rw.git
cd linux-apfs-rw
time make
# insert into kernel
sudo modprobe libcrc32c
sudo insmod apfs.ko

# Now mount your APFS drive by clicking it in your GUI file manager
```

You can analyze the disk space usage on the drive by cd-ing into the mounted APFS filesystem now and running this:
```bash
# see contents
sudo ncdu # sudo is **required** to see all contents!
```

**Comment by ElectricRCAircraftGuy** [comment]
I just wrote this, referencing the content above: [Super User: How to mount Apple APFS filesystems](https://superuser.com/a/1785629/425838)
