### ISSUE TITLE
Documentation: how to build `linux-apfs-rw` on a fresh Linux Ubuntu live USB, to get data from a MacBook

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [linux-apfs/linux-apfs-rw#45]
First off, great tool. Thank you! 

If you activate the Wiki for this repo, in the repo settings, I'll write a bit of documentation about this for you. Otherwise, the purpose of this issue is simply to point to some resources to help others, including my rapid installation script which runs great on a brand new Ubuntu 22.04 live USB session, to quickly get your tool installed. 

See here: [Super User: How to mount Apple APFS filesystems](https://superuser.com/a/1785629/425838) - see my `install_linux-apfs-rw.sh` installation script there.

Bigger writeup of my whole recovery project is on my website here: [How to repair your MacBook when it won’t boot](https://gabrielstaples.com/repairing-macbook/)

Your tool works great for unencrypted Apple APFS filesystems. I hope you get encrypted ones working soon, too. Thanks again.

Related issue: https://github.com/linux-apfs/linux-apfs-rw/issues/42#issuecomment-1556103266

**Comment by ElectricRCAircraftGuy** [comment]
You can close this issue if you want, or leave it open to make it more searchable for others, or activate a community wiki on this repo and leave it open until I add a blurb to the wiki. Your call. Let me know what you want to do.

**Comment by eafer** [comment]
I don't know if there's that much content to put on a wiki, but it's fine if you want to start it. It should be enabled now.
