### ISSUE TITLE
Skipping BTF generation

### ISSUE THREAD

**Issue by BlackMage2** [linux-apfs/linux-apfs-rw#48]
During compiling i get the warning:` Skipping BTF generation for /home/sven/Development/linux-apfs-rw/apfs.ko due to unavailability of vmlinux`

what does that mean?

**Comment by eafer** [comment]
I'm not sure that qualifies as a warning, and the driver will work anyway. If you really want it gone I found this: https://askubuntu.com/questions/1348250/skipping-btf-generation-xxx-due-to-unavailability-of-vmlinux-on-ubuntu-21-04
