### ISSUE TITLE
module fails to build for Linux 6.5: detected write beyond size of object

### ISSUE THREAD

**Issue by alexmyczko** [linux-apfs/linux-apfs-rw#49]
Thank you for considering:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043112

**Comment by eafer** [comment]
I just pushed two patches that should fix this, but I don't see the strcpy() error over here (I'm guessing it's a configuration option I'm not using), so let me know if it's still broken somehow.

**Comment by eafer** [comment]
I just made a release, so I guess I can close this.

**Comment by daniele-athome** [comment]
This is still present on Debian testing with kernel 6.5.0 (using apfs from unstable which is 0.3.3+git20230810+ds-1.
