### ISSUE TITLE
Is there any plan to upstream the driver in future?

### ISSUE THREAD

**Issue by chromer030** [linux-apfs/linux-apfs-rw#55]
Thanks for your efforts, it's really a huge step to have APFS on Linux with all challenges.

Have you any plant for upstream support?

**Comment by eafer** [comment]
The driver is still very far from being ready for upstream. Even if we get there, there is no guarantee that upstream we'll want it. But sure, I'll try to submit someday; it would be nice to stop worrying about supporting all kernel versions. Do you need this to be upstream for any particular reason?

**Comment by chromer030** [comment]
> Do you need this to be upstream for any particular reason?

No i was just curious and it's very easy and fun to have a driver by default.
