### ISSUE TITLE
Fails to install on Linux Mint kernel 6.2

### ISSUE THREAD

**Issue by xandeale** [linux-apfs/linux-apfs-rw#57]
sudo make install
make -C /lib/modules/6.2.0-36-generic/build M=/home/home/linux-apfs-rw modules_install
make[1]: Entering directory '/usr/src/linux-headers-6.2.0-36-generic'
  INSTALL /lib/modules/6.2.0-36-generic/extra/apfs.ko
  SIGN    /lib/modules/6.2.0-36-generic/extra/apfs.ko
  DEPMOD  /lib/modules/6.2.0-36-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-6.2.0-36-generic'

**Comment by eafer** [comment]
The kernel build system seems to expect a `System.map` file in `/lib/modules/6.2.0-36-generic/build/System.map`, but the file is probably in `/boot/System.map-6.2.0-36-generic`. I don't really know who is to blame for this confusion, but I don't think there's anything I can do about it. You can make a symlink to `System.map` in the right location, or you can just run `depmod -A` by hand yourself after `make install`, and it should work.

I wonder if `make install` is really what you want though, maybe you'd be better off using dkms, or checking if your distro has a package for the driver.

**Comment by xandeale** [comment]
It worked on Arcolinux on read-only mode when installed from AUR , but i also tried installing apfs package from mint/ubuntu's repo and it doesn't work.

**Comment by eafer** [comment]
You say it doesn't mount with the ubuntu package? That's weird, which package version did you try?

**Comment by xandeale** [comment]
i tried apfs-dkms on mint store and it didn't mount the partition.

**Comment by eafer** [comment]
Can you check the exact package version? Like with `dpkg -s <package> | grep Version`?

**Comment by xandeale** [comment]
apfs-dkms
Version: 0+git20220214+ds-2ubuntu2~22.04.2

**Comment by eafer** [comment]
That's a bit old, I guess only newer ubuntu releases are getting apfs updates. You can set dkms up on your own though, if you want the driver to keep working when the kernel gets updated.

**Comment by xandeale** [comment]
Thanks for help, I found a working version of apfs-dkms at Ubuntu launchpad, the one that worked is 0.3.2 for ubuntu 24.04
