### ISSUE TITLE
Make Falis on kernel 6.7.5 Fedora 39 workstation

### ISSUE THREAD

**Issue by red-smeg** [linux-apfs/linux-apfs-rw#63]
Running make on Fedora Workstation 39.  I have verified the kernel headers and devel are installed

`sudo dnf install kernel-headers kernel-devel

Fedora 39 - x86_64 - Updates                                                                         56 kB/s |  22 kB     00:00    
Fedora 39 - x86_64 - Updates                                                                        1.2 MB/s | 2.4 MB     00:01    
symfony-stable                                                                                      1.9 kB/s | 659  B     00:00    
symfony-stable-noarch                                                                               2.2 kB/s | 659  B     00:00    
symfony-stable-source                                                                               2.4 kB/s | 659  B     00:00    
Package kernel-headers-6.7.3-200.fc39.x86_64 is already installed.
Package kernel-devel-6.7.3-200.fc39.x86_64 is already installed.
Package kernel-devel-6.7.4-200.fc39.x86_64 is already installed.
Package kernel-devel-6.7.5-200.fc39.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
`
run make and get 

`$ sudo make
scripts/kconfig/conf  --syncconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
make[2]: *** [scripts/kconfig/Makefile:69: syncconfig] Error 1
make[1]: *** [Makefile:544: syncconfig] Error 2
Makefile:600: include/config/auto.conf: No such file or directory
make: *** [Makefile:640: include/config/auto.conf] Error 2
`

uname -r = '6.7.5-200.fc39.x86_64'

**Comment by red-smeg** [comment]
running Xorg and gnome if that information helps

**Comment by eafer** [comment]
Are you running make from inside the linux-apfs-rw directory? I'm confused because the first thing you should see is a line like

```
make -C /lib/modules/6.7.5-200.fc39.x86_64/build M=<path to linux-apfs-rw>
```

that jumps to the kernel Makefile.

**Comment by red-smeg** [comment]
I ended up destroying the clone and redoing it and the make now gives this output 

` ./genver.sh
make -C /lib/modules/6.7.5-200.fc39.x86_64/build M=/home/mark/Documents/GitHub/linux-apfs-rw
make[1]: Entering directory '/usr/src/kernels/6.7.5-200.fc39.x86_64'
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/btree.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/compress.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/dir.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/extents.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/file.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/inode.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/key.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/libzbitmap.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/lzfse/lzfse_decode.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/lzfse/lzfse_decode_base.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/lzfse/lzfse_fse.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/lzfse/lzvn_decode_base.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/message.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/namei.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/node.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/object.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/snapshot.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/spaceman.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/super.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/symlink.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/transaction.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/unicode.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/xattr.o
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/xfield.o
  LD [M]  /home/mark/Documents/GitHub/linux-apfs-rw/apfs.o
/home/mark/Documents/GitHub/linux-apfs-rw/apfs.o: warning: objtool: lzvn_decode+0x159: sibling call from callable instruction with modified stack frame
  MODPOST /home/mark/Documents/GitHub/linux-apfs-rw/Module.symvers
  CC [M]  /home/mark/Documents/GitHub/linux-apfs-rw/apfs.mod.o
  LD [M]  /home/mark/Documents/GitHub/linux-apfs-rw/apfs.ko
  BTF [M] /home/mark/Documents/GitHub/linux-apfs-rw/apfs.ko
Skipping BTF generation for /home/mark/Documents/GitHub/linux-apfs-rw/apfs.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/kernels/6.7.5-200.fc39.x86_64'
  `
I will close the issue..
