### ISSUE TITLE
Any method to list the APFS volumes with their labels

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#69]
I have an APFS container with many volumes. Is there any command I can use to list the volumes with their names?

**Comment by AdityaGarg8** [comment]
Or is there any way I can mount a volume by their LABEL instead of volume number

**Comment by eafer** [comment]
Neither are implemented so far. The second would probably be much easier. I'll look into it as soon as I have the time.

**Comment by eafer** [comment]
I'm looking into this now, and mounting by label is actually impossible because apple allows multiple volumes to share the same label. I guess I could write a tool to list the labels.

**Comment by AdityaGarg8** [comment]
> I'm looking into this now, and mounting by label is actually impossible because apple allows multiple volumes to share the same label. I guess I could write a tool to list the labels.

LGTM. Maybe we could also make the file managers display the label being mounted as well.

**Comment by eafer** [comment]
Hey I just pushed a tool to list labels, when you can please try it out and let me know if it helps. As for the file managers, I'm not completely sure how they get the label information, but I think it requires filesystem-specific plugins for udisks.

**Comment by AdityaGarg8** [comment]
> Hey I just pushed a tool to list labels, when you can please try it out and let me know if it helps. As for the file managers, I'm not completely sure how they get the label information, but I think it requires filesystem-specific plugins for udisks.

I'll check it out when I get free.
Thanks!

**Comment by eafer** [comment]
I made a release for apfsprogs a few days ago that has this tool you requested. I guess I'll close this now, feel free to reopen if it doesn't work for you.
