### ISSUE TITLE
Doesn't compile on 6.10

### ISSUE THREAD

**Issue by AdityaGarg8** [linux-apfs/linux-apfs-rw#71]
Any idea when will a 6.10 compatible release be published

**Comment by eafer** [comment]
Have you tried the development branch? I usually only make a tag for the new kernel version on the last release candidate, in case the build breaks again.

**Comment by AdityaGarg8** [comment]
> Have you tried the development branch? I usually only make a tag for the new kernel version after the last release candidate, in case the build breaks again.

I ported the necessary change for 6.10 from your development branch. Thanks!
