### ISSUE TITLE
Build fails with 6.10

### ISSUE THREAD

**Issue by ymatsiuk** [linux-apfs/linux-apfs-rw#73]
The error is:
```
/build/source/super.c: In function 'apfs_sb_set_blocksize':
/build/source/super.c:60:39: error: passing argument 1 of 'set_blocksize' from incompatible pointer type [-Werror=incompatible-pointer-types]
   60 |         if (set_blocksize(APFS_NXI(sb)->nx_bdev, size))
      |                           ~~~~~~~~~~~~^~~~~~~~~
      |                                       |
      |                                       struct block_device *
In file included from /build/source/super.c:7:
/nix/store/hlhp0pprnyq96npl2k1b5z9iy2xc4c9q-linux-6.10-dev/lib/modules/6.10.0/source/include/linux/blkdev.h:1495:32: note: expected 'struct file *' but argument is of type 'struct block_device *'
 1495 | int set_blocksize(struct file *file, int size);
      |                   ~~~~~~~~~~~~~^~~~
```
Most probably related to [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.10&id=d18a8679581e8d1166b68e211d16c5349ae8c38c) & [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.10&id=ead083aeeed9df44fab9227e47688f7305c3a233)..

**Comment by eafer** [comment]
Those errors should have already been fixed here: https://github.com/linux-apfs/linux-apfs-rw/commit/071cdacc32e15c6121b925c130ff6b509dfc5693. Are you building the latest tag (0.3.10)?

**Comment by Luflosi** [comment]
This issue can be closed.
NixOS still ships 0.3.9 because my PR updating it to 0.3.10 hasn't been merged yet: https://github.com/NixOS/nixpkgs/pull/327490.

**Comment by ymatsiuk** [comment]
OMG, apologies for this, I should've checked the code first :blush:

**Comment by eafer** [comment]
No problem.
