### ISSUE TITLE
insmod: Key was rejected by service

### ISSUE THREAD

**Issue by prateekmedia** [linux-apfs/linux-apfs-rw#80]
I followed the instructions from readme, and in the insmod apfs.ko step I am unable to run this command successfully.

First if I run it barely it results in: `Operation not permitted`

And if I try running with sudo it results in: `insmod: ERROR: could not insert module apfs.ko: Key was rejected by service`

Am I missing something?

Kernel: 6.10.11-200
Distro: Fedora 40

**Comment by eafer** [comment]
I've never seen that error message myself, but apparently it's because of secure boot: https://askubuntu.com/questions/1455528/modprobe-key-was-rejected-by-service-ubuntu-22-04-1-desktop-iso.

**Comment by eafer** [comment]
I guess I can close this, feel free to reopen if you still have questions.
