### ISSUE TITLE
insmod: ERROR: could not insert module apfs.ko: Invalid module format

### ISSUE THREAD

**Issue by BlackMage2** [linux-apfs/linux-apfs-rw#84]
i have compiled the module successfull, but insmod fails: '_insmod: ERROR: could not insert module apfs.ko: Invalid module format_' how i can fix that? (Linux version 6.2.0-35-generic)

how i can fix that? I don't understand why the module can't be loaded.

**Comment by BlackMage2** [comment]
no, no sign. Something is wrong with the code from the module. can I somehow see more at insmod?

**Comment by BlackMage2** [comment]
but libcrc32c.ko exist in my system at /lib/modules/6.2.0-35-generic/kernel/lib

**Comment by eafer** [comment]
> can I somehow see more at insmod?

Well, I would have expected more info on dmesg. I'm surprised you are getting nothing. Maybe you could also check `modinfo ./apfs.ko` after the build.

> Something is wrong with the code from the module

I can't discard it, but it seems unlikely? I have built for 6.2 kernels in the past with no problems, though not your exact distro version. I assume you followed the build instructions from the readme step by step, starting from scratch?

**Comment by BlackMage2** [comment]
```
$ modinfo ./apfs.ko
filename:       /home/sven2/build/linux-apfs-rw/./apfs.ko
license:        GPL
version:        v0.3.12
description:    Apple File System
author:         Ernesto A. Fernández
alias:          fs-apfs
srcversion:     04D0B6B7CF603BB0ECC8FAF
depends:        libcrc32c
retpoline:      Y
name:           apfs
vermagic:       6.2.0-35-generic SMP preempt mod_unload modversions
```

**Comment by eafer** [comment]
I just tried a build for 6.2.0-39-generic and it seems to work fine. I'm not sure what your problem could be.

**Comment by BlackMage2** [comment]
I couldn't figure out what was wrong. but a manual installation with 'dkms install . --force' worked.

**Comment by eafer** [comment]
Good to hear, I guess I'll close this now.
